#!/usr/bin/env bash
# Build, sign and install HU Probe.
#
# No Gradle. Uses the Android SDK command-line tools directly, which is enough
# for a single-activity app with no resources.
#
#   ./build.sh                build + install to the connected device
#   ./build.sh --no-install   build only
#
# Override any of these if your layout differs:
#   ANDROID_SDK   default: $ANDROID_HOME, else ~/AppData/Local/Android/Sdk (Windows)
#                          or ~/Android/Sdk (Linux/macOS)
#   BUILD_TOOLS   default: highest version found
#   PLATFORM      default: highest android-NN found
#   JAVA_HOME     default: whatever javac is on PATH
set -e

here="$(cd "$(dirname "$0")" && pwd)"
repo="$(dirname "$here")"

# ---- locate the SDK -------------------------------------------------------
if [ -z "$ANDROID_SDK" ]; then
  for c in "$ANDROID_HOME" "$HOME/AppData/Local/Android/Sdk" "$HOME/Android/Sdk" \
           "$HOME/Library/Android/sdk"; do
    [ -n "$c" ] && [ -d "$c/platform-tools" ] && ANDROID_SDK="$c" && break
  done
fi
[ -d "$ANDROID_SDK" ] || { echo "ANDROID_SDK not found; set it explicitly"; exit 1; }

BUILD_TOOLS="${BUILD_TOOLS:-$(ls -1 "$ANDROID_SDK/build-tools" | sort -V | tail -1)}"
PLATFORM="${PLATFORM:-$(ls -1 "$ANDROID_SDK/platforms" | grep -E '^android-[0-9]+$' | sort -V | tail -1)}"
BT="$ANDROID_SDK/build-tools/$BUILD_TOOLS"
AJ="$ANDROID_SDK/platforms/$PLATFORM/android.jar"
ADB="$ANDROID_SDK/platform-tools/adb"
[ -f "$ADB" ] || ADB="$ADB.exe"

# Resolve a build-tool by name, allowing for Windows .bat/.exe suffixes.
bt() {
  for e in "" ".bat" ".exe" ".cmd"; do
    [ -f "$BT/$1$e" ] && { echo "$BT/$1$e"; return; }
  done
  echo "build-tool not found: $1 (looked in $BT)" >&2; exit 1
}

JAVAC="$(command -v javac || true)"
[ -n "$JAVA_HOME" ] && JAVAC="$JAVA_HOME/bin/javac"
[ -n "$JAVAC" ] || { echo "javac not found; set JAVA_HOME"; exit 1; }

echo "sdk=$ANDROID_SDK  build-tools=$BUILD_TOOLS  platform=$PLATFORM"

rm -rf "$here/build"; mkdir -p "$here/build/classes"

# ---- generate Names.java from the extracted constant table ----------------
table="$repo/data/U_AIR_table.txt"
{
  echo "package com.probe.hu;"; echo
  echo "import java.util.HashMap;"; echo "import java.util.Map;"; echo
  echo "/** Generated by build.sh from data/U_AIR_table.txt. Do not hand-edit. */"
  echo "final class Names {"
  echo "    private static final Map<Integer,String> M = new HashMap<Integer,String>();"
  echo "    static {"
  awk -F= '$1!="U_AIR_BEGIN" && $1!="U_AIR_END" {printf "        M.put(%s, \"%s\");\n", $2, $1}' "$table"
  echo "    }"; echo
  echo "    static final int[] CODES = {"
  awk -F= '$1!="U_AIR_BEGIN" && $1!="U_AIR_END" {print $2}' "$table" | sort -n -u \
    | awk 'BEGIN{printf "        "} {printf "%s, ", $0; if(++n%14==0) printf "\n        "} END{printf "\n"}'
  echo "    };"; echo
  echo "    static String of(int code) {"
  echo "        String n = M.get(code);"
  echo "        return n != null ? n : (\"code_\" + code);"
  echo "    }"
  echo "}"
} > "$here/src/com/probe/hu/Names.java"

# ---- compile / dex / package / sign ---------------------------------------
"$JAVAC" -nowarn -source 11 -target 11 -classpath "$AJ" \
    -d "$here/build/classes" "$here"/src/com/probe/hu/*.java 2>&1 | grep -vE 'warning|^Note' || true

"$(bt d8)" --lib "$AJ" --min-api 26 --output "$here/build/" \
    $(find "$here/build/classes" -name '*.class') >/dev/null

"$(bt aapt2)" link -I "$AJ" --manifest "$here/AndroidManifest.xml" \
    --min-sdk-version 26 --target-sdk-version 33 -o "$here/build/unsigned.apk"

cd "$here/build"
python -c "
import zipfile
z = zipfile.ZipFile('unsigned.apk','a',zipfile.ZIP_DEFLATED)
z.write('classes.dex','classes.dex'); z.close()"

"$(bt zipalign)" -p -f 4 unsigned.apk aligned.apk
rm -f huprobe.apk huprobe.apk.idsig

ks="${KEYSTORE:-$HOME/.android/debug.keystore}"
if [ ! -f "$ks" ]; then
  echo "generating debug keystore at $ks"
  mkdir -p "$(dirname "$ks")"
  keytool -genkeypair -keystore "$ks" -storepass android -keypass android \
    -alias androiddebugkey -keyalg RSA -keysize 2048 -validity 10950 \
    -dname "CN=Android Debug,O=Android,C=US" >/dev/null 2>&1
fi

"$(bt apksigner)" sign --ks "$ks" --ks-pass pass:android --key-pass pass:android \
    --ks-key-alias androiddebugkey --out huprobe.apk aligned.apk 2>&1 \
  | grep -viE 'warning|restricted' || true

echo "built: $(wc -c < huprobe.apk) bytes"

# ---- install ---------------------------------------------------------------
if [ "$1" != "--no-install" ]; then
  target="$DEVICE"
  if [ -z "$target" ]; then
    target=$("$ADB" mdns services 2>/dev/null | grep '_adb-tls-connect' | awk '{print $3}' | head -1)
  fi
  if [ -n "$target" ]; then
    "$ADB" connect "$target" >/dev/null 2>&1
    "$ADB" -s "$target" install -r huprobe.apk 2>&1 | tail -1
    echo "device: $target"
  else
    "$ADB" install -r huprobe.apk 2>&1 | tail -1
  fi
fi
