#!/usr/bin/env bash
# Generate Tables.java from the extracted constant tables in data/.
# Called by build.sh; run standalone if you edit the tables by hand.
set -e
here="$(cd "$(dirname "$0")" && pwd)"
data="$(dirname "$here")/data"
out="$here/src/com/probe/hu/Tables.java"

emit_map() {   # $1=java map var  $2..=table files
  local var="$1"; shift
  for f in "$@"; do
    [ -f "$f" ] || continue
    awk -F= -v v="$var" '$1!~/_BEGIN$/ && $1!~/_END$/ && $1!="U_CNT_MAX" && $1!="U_SPECTRUM" {
      printf "        %s.put(%s, \"%s\");\n", v, $2, $1 }' "$f"
  done
}
emit_codes() { # $1..=table files
  for f in "$@"; do [ -f "$f" ] && awk -F= '$1!~/_BEGIN$/ && $1!~/_END$/ && $1!="U_CNT_MAX" && $1!="U_SPECTRUM" {print $2}' "$f"; done \
    | sort -n -u | awk 'BEGIN{printf "        "} {printf "%s, ", $0; if(++n%14==0) printf "\n        "} END{printf "\n"}'
}

{
echo "package com.probe.hu;"
echo
echo "import java.util.HashMap;"
echo "import java.util.Map;"
echo
echo "/** Generated by gen-tables.sh from data/*.txt. Do not hand-edit. */"
echo "final class Tables {"
echo
echo "    static final class Mod {"
echo "        final int id; final String label; final int[] codes;"
echo "        final Map<Integer,String> names;"
echo "        Mod(int id, String label, int[] codes, Map<Integer,String> names) {"
echo "            this.id = id; this.label = label; this.codes = codes; this.names = names;"
echo "        }"
echo "        String of(int code) {"
echo "            String n = names.get(code);"
echo "            return n != null ? n : (label + \"_code_\" + code);"
echo "        }"
echo "    }"
echo

i=0
for spec in "0:MAIN:$data/U_MAIN_table.txt" \
            "4:SOUND:$data/U_SOUND_table.txt" \
            "7:CANBUS:$data/U_AIR_table.txt $data/U_CANBUS_table.txt" \
            "10:STEER:$data/U_STEER_table.txt"; do
  id="${spec%%:*}"; rest="${spec#*:}"; label="${rest%%:*}"; files="${rest#*:}"
  echo "    private static final Map<Integer,String> N$i = new HashMap<Integer,String>();"
  echo "    static {"
  emit_map "N$i" $files
  echo "    }"
  echo "    private static final int[] C$i = {"
  emit_codes $files
  echo "    };"
  echo
  i=$((i+1))
done

echo "    static final Mod[] ALL = {"
echo "        new Mod(0,  \"MAIN\",   C0, N0),"
echo "        new Mod(4,  \"SOUND\",  C1, N1),"
echo "        new Mod(7,  \"CANBUS\", C2, N2),"
echo "        new Mod(10, \"STEER\",  C3, N3),"
echo "    };"
echo "}"
} > "$out"

echo "generated $(basename "$out"): $(grep -c '\.put(' "$out") constants across 4 modules"
